kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: dags-pv-volume
spec:
  storageClassName: local 
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /airflow-dags/
--- 
kind: PersistentVolumeClaim 
apiVersion: v1 
metadata: 
  name: dags-pv-claim 
spec: 
  storageClassName: local 
  accessModes: 
    - ReadOnlyMany 
  resources: 
    requests: 
      storage: 5Gi 