---
# Source: airflow/templates/rbac/pod-launcher-role.yaml
################################
## Airflow Pod Launcher Role
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-launcher-role
  namespace: "local-airflow"
  labels:
    tier: airflow
    release: release-name
    chart: "airflow-1.10.0"
    heritage: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "create"
      - "list"
      - "get"
      - "patch"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "create"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "list"
