---
# Source: airflow/templates/rbac/pod-launcher-rolebinding.yaml
################################
## Airflow Pod Launcher Role Binding
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "local-airflow"
  name: pod-launcher-rolebinding
  labels:
    tier: airflow
    release: release-name
    chart: "airflow-1.10.0"
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-launcher-role
subjects:
  - kind: ServiceAccount
    name: airflow-scheduler-serviceaccount
    namespace: "local-airflow"
