---
# Source: airflow/templates/scheduler/scheduler-serviceaccount.yaml
################################
## Airflow Scheduler ServiceAccount
#################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-sa
  namespace: local-airflow
